
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;




public class PlaceOrderGUI extends javax.swing.JFrame {
        Connection con;
        PreparedStatement pst;
    

    /**
     * Creates new form PlaceOrderGUI
     */
    public PlaceOrderGUI() {
        initComponents();
        txtbill.setText("");
        con = SQLCON.connect();
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAddItems = new javax.swing.JButton();
        txtbill = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPlaceOrder = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        chkfd1 = new javax.swing.JCheckBox();
        txtfd1 = new javax.swing.JSpinner();
        chkfd2 = new javax.swing.JCheckBox();
        txtfd2 = new javax.swing.JSpinner();
        chkfd3 = new javax.swing.JCheckBox();
        txtfd3 = new javax.swing.JSpinner();
        chkfd4 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtfd4 = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        chkM1 = new javax.swing.JCheckBox();
        spM3 = new javax.swing.JSpinner();
        chkM3 = new javax.swing.JCheckBox();
        spM1 = new javax.swing.JSpinner();
        chkM4 = new javax.swing.JCheckBox();
        chkM2 = new javax.swing.JCheckBox();
        spM2 = new javax.swing.JSpinner();
        spM4 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        chkD1 = new javax.swing.JCheckBox();
        spD1 = new javax.swing.JSpinner();
        spD2 = new javax.swing.JSpinner();
        spD4 = new javax.swing.JSpinner();
        spD3 = new javax.swing.JSpinner();
        chkD3 = new javax.swing.JCheckBox();
        chkD4 = new javax.swing.JCheckBox();
        chkD2 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Place Order");

        jPanel1.setBackground(new java.awt.Color(73, 121, 107));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1.setBackground(new java.awt.Color(49, 120, 115));
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(225, 225, 225));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Price", "Qty", "Total"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(163, 193, 173));
        jTable1.setSelectionForeground(new java.awt.Color(204, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        btnAddItems.setBackground(new java.awt.Color(163, 193, 173));
        btnAddItems.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnAddItems.setForeground(new java.awt.Color(51, 51, 255));
        btnAddItems.setText("Add Items");
        btnAddItems.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemsActionPerformed(evt);
            }
        });

        txtbill.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtbill.setText("000");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Grand Total");

        btnPlaceOrder.setBackground(new java.awt.Color(163, 193, 173));
        btnPlaceOrder.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(163, 193, 173));

        chkfd1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkfd1.setText("Lemonade");
        chkfd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkfd1ActionPerformed(evt);
            }
        });

        txtfd1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        chkfd2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkfd2.setText("Apple Juice");
        chkfd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkfd2ActionPerformed(evt);
            }
        });

        txtfd2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        chkfd3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkfd3.setText("Hot Chocolate");
        chkfd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkfd3ActionPerformed(evt);
            }
        });

        txtfd3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        chkfd4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkfd4.setText("Espresso");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lemonade.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apple juice.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hot chocolate.png"))); // NOI18N
        jLabel9.setText("jLabel9");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Espresso.png"))); // NOI18N
        jLabel10.setText("jLabel10");

        txtfd4.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtfd3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkfd3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(chkfd4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtfd4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(chkfd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtfd1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(txtfd2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(67, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(chkfd2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkfd1)
                    .addComponent(chkfd2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(chkfd4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtfd4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkfd3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(txtfd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Beverages", jPanel2);

        jPanel3.setBackground(new java.awt.Color(163, 193, 173));

        chkM1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkM1.setText("Kottu");
        chkM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkM1ActionPerformed(evt);
            }
        });

        spM3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        chkM3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkM3.setText("Pasta");
        chkM3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkM3ActionPerformed(evt);
            }
        });

        spM1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        chkM4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkM4.setText("Pizza");
        chkM4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkM4ActionPerformed(evt);
            }
        });

        chkM2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkM2.setText("Fried Rice");
        chkM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkM2ActionPerformed(evt);
            }
        });

        spM2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        spM4.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kottu-chicken.png"))); // NOI18N
        jLabel11.setText("jLabel11");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fried rice.png"))); // NOI18N
        jLabel12.setText("jLabel12");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pasta.png"))); // NOI18N
        jLabel13.setText("jLabel13");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza.png"))); // NOI18N
        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spM3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spM1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chkM1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkM3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(spM2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkM2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(29, 29, 29)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkM4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spM4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkM1)
                    .addComponent(chkM2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkM3)
                    .addComponent(chkM4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spM4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel11.getAccessibleContext().setAccessibleName("");

        jTabbedPane1.addTab("Meals", jPanel3);

        jPanel4.setBackground(new java.awt.Color(163, 193, 173));

        chkD1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkD1.setText("Caramel Pudding");
        chkD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkD1ActionPerformed(evt);
            }
        });

        spD1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        spD2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        spD4.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        spD3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        chkD3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkD3.setText("Chocolate Moose");
        chkD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkD3ActionPerformed(evt);
            }
        });

        chkD4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkD4.setText("Lava Cake");
        chkD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkD4ActionPerformed(evt);
            }
        });

        chkD2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkD2.setText("Biscuit Pudding");
        chkD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkD2ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caramel.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biscuit-pudding.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chocolate Mousse.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lava.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(chkD1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chkD2)))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel2))
                            .addComponent(spD1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkD3)
                            .addComponent(spD3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(chkD4)
                                    .addComponent(spD4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spD2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkD1)
                    .addComponent(chkD2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(spD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkD4)
                    .addComponent(chkD3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spD4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Deserts", jPanel4);

        btnDelete.setBackground(new java.awt.Color(163, 193, 173));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 0, 0));
        btnDelete.setText("Remove Items");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(163, 193, 173));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLogOut.setText("Logout");
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Place Order");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(btnDelete))
                                .addGap(18, 18, 18)
                                .addComponent(txtbill, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLogOut)
                            .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(312, 312, 312))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtbill)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDelete)
                                .addGap(32, 32, 32)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddItems)
                    .addComponent(btnPlaceOrder))
                .addGap(58, 58, 58)
                .addComponent(btnLogOut)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    DefaultTableModel model;


    private void chkfd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkfd3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkfd3ActionPerformed

    private void btnAddItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemsActionPerformed
        // TODO add your handling code here:

        int sum = 0;

        if (chkfd1.isSelected()) {
            String lemonade = "Lemonade";
            int price = 250;
            int qty = Integer.parseInt(txtfd1.getValue().toString());
            int tot = price * qty;
            model = (DefaultTableModel) jTable1.getModel();

            model.addRow(new Object[]{
                lemonade,
                price,
                qty,
                tot
            }
            );
        }
        if (chkfd2.isSelected()) {
            String appleJ = "Apple Juice";
            int price = 300;
            int qty = Integer.parseInt(txtfd2.getValue().toString());
            int tot = price * qty;
            model = (DefaultTableModel) jTable1.getModel();

            model.addRow(new Object[]{
                appleJ,
                price,
                qty,
                tot
            }
            );
        }

        if (chkfd3.isSelected()) {
            String hChocolate = "Hot Chocolate";
            int price = 400;
            int qty = Integer.parseInt(txtfd3.getValue().toString());
            int tot = price * qty;
            model = (DefaultTableModel) jTable1.getModel();

            model.addRow(new Object[]{
                hChocolate,
                price,
                qty,
                tot
            }
            );
        }

        if (chkfd4.isSelected()) {
            String espresso = "Espresso";
            int price = 380;
            int qty = Integer.parseInt(txtfd4.getValue().toString());
            int tot = price * qty;
            model = (DefaultTableModel) jTable1.getModel();

            model.addRow(new Object[]{
                espresso,
                price,
                qty,
                tot
            }
            );
        }
        /*Meals*/
        if (chkM1.isSelected()) {
            String kottu = "Kottu";
            int price = 800;
            int qty = Integer.parseInt(spM1.getValue().toString());
            int tot = price * qty;
            model = (DefaultTableModel) jTable1.getModel();

            model.addRow(new Object[]{
                kottu,
                price,
                qty,
                tot
            }
            );
        }
        
        if (chkM2.isSelected()) {
            String friedR = "Fried Rice";
            int price = 1200;
            int qty = Integer.parseInt(spM2.getValue().toString());
            int tot = price * qty;
            model = (DefaultTableModel) jTable1.getModel();

            model.addRow(new Object[]{
                friedR,
                price,
                qty,
                tot
            }
            );
        }
        
        if (chkM3.isSelected()) {
            String pasta = "Pasta";
            int price = 1300;
            int qty = Integer.parseInt(spM3.getValue().toString());
            int tot = price * qty;
            model = (DefaultTableModel) jTable1.getModel();

            model.addRow(new Object[]{
                pasta,
                price,
                qty,
                tot
            }
            );
        }
        
        if (chkM4.isSelected()) {
            String pizza = "Pizza";
            int price = 1800;
            int qty = Integer.parseInt(spM4.getValue().toString());
            int tot = price * qty;
            model = (DefaultTableModel) jTable1.getModel();

            model.addRow(new Object[]{
                pizza,
                price,
                qty,
                tot
            }
            );
        }
        
        /*Deserts*/
        
        if (chkD1.isSelected()) {
            String caramel = "Caramel Pudding";
            int price = 250;
            int qty = Integer.parseInt(spD1.getValue().toString());
            int tot = price * qty;
            model = (DefaultTableModel) jTable1.getModel();

            model.addRow(new Object[]{
                caramel,
                price,
                qty,
                tot
            }
            );
        }
        
        if (chkD2.isSelected()) {
            String biscuit = "Biscuit Pudding";
            int price = 300;
            int qty = Integer.parseInt(spD2.getValue().toString());
            int tot = price * qty;
            model = (DefaultTableModel) jTable1.getModel();

            model.addRow(new Object[]{
                biscuit,
                price,
                qty,
                tot
            }
            );
        }
        
        if (chkD3.isSelected()) {
            String chocalateMoo = "Chocalate Moose";
            int price = 350;
            int qty = Integer.parseInt(spD3.getValue().toString());
            int tot = price * qty;
            model = (DefaultTableModel) jTable1.getModel();

            model.addRow(new Object[]{
                chocalateMoo,
                price,
                qty,
                tot
            }
            );
        }
        
        if (chkD4.isSelected()) {
            String lava = "Lava Cake";
            int price = 360;
            int qty = Integer.parseInt(spD4.getValue().toString());
            int tot = price * qty;
            model = (DefaultTableModel) jTable1.getModel();

            model.addRow(new Object[]{
                lava,
                price,
                qty,
                tot
            }
            );
        }
        
        //Empty Add Items Button validation
        if((chkfd1.isSelected() == false) && (chkfd2.isSelected() == false)&&
           (chkfd3.isSelected() == false) && (chkfd4.isSelected() == false)&&
           (chkM1.isSelected() == false) && (chkM2.isSelected() == false)&&
           (chkM3.isSelected() == false) && (chkM4.isSelected() == false)&&
           (chkD1.isSelected() == false) && (chkD2.isSelected() == false)&&
           (chkD3.isSelected() == false) && (chkD4.isSelected() == false))
        {
             JOptionPane.showMessageDialog(null, "No Food Item is Select to Add order");
        
        }
        
        //Reset Check box
        chkfd1.setSelected(false);
        chkfd2.setSelected(false);
        chkfd3.setSelected(false);
        chkfd4.setSelected(false);
        
        chkM1.setSelected(false);
        chkM2.setSelected(false);
        chkM3.setSelected(false);
        chkM4.setSelected(false);
        
        chkD1.setSelected(false);
        chkD2.setSelected(false);
        chkD3.setSelected(false);
        chkD4.setSelected(false);
        
        
        
        //Reset the Spinner value
        txtfd1.setValue(((SpinnerNumberModel) txtfd1.getModel()).getMinimum());
        txtfd2.setValue(((SpinnerNumberModel) txtfd2.getModel()).getMinimum());
        txtfd3.setValue(((SpinnerNumberModel) txtfd3.getModel()).getMinimum());
        txtfd4.setValue(((SpinnerNumberModel) txtfd4.getModel()).getMinimum());
        
        spM1.setValue(((SpinnerNumberModel) spM1.getModel()).getMinimum());
        spM2.setValue(((SpinnerNumberModel) spM2.getModel()).getMinimum());
        spM3.setValue(((SpinnerNumberModel) spM3.getModel()).getMinimum());
        spM4.setValue(((SpinnerNumberModel) spM4.getModel()).getMinimum());
        
        spD1.setValue(((SpinnerNumberModel) spD1.getModel()).getMinimum());
        spD2.setValue(((SpinnerNumberModel) spD2.getModel()).getMinimum());
        spD3.setValue(((SpinnerNumberModel) spD3.getModel()).getMinimum());
        spD4.setValue(((SpinnerNumberModel) spD4.getModel()).getMinimum());
        
        
        
        
        

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtbill.setText(Integer.toString(sum));

    }//GEN-LAST:event_btnAddItemsActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        // TODO add your handling code here:
        int sum =0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtbill.setText(Integer.toString(sum));
        
        
       
        
        //Remove all data in Table
      //  DefaultTableModel tb1Model = (DefaultTableModel) jTable1.getModel();
       // tb1Model.setRowCount(0);
        
       txtbill.setText("");
        
        
    /*order_table Database*/    
        
        
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        if(dtm.getRowCount()==0){
        //show message if table is empty
        JOptionPane.showMessageDialog(this, "Table is Empty");
             }else{
    //if table is not empty
         String Item,Price,Qty,Total;
            try {
                
                JOptionPane.showMessageDialog(rootPane, "The Grand Total is: "+sum+ "/=", "Place Order", 1);

    
            for (int i=0;i<dtm.getRowCount();i++)
            {
                Item = dtm.getValueAt(i, 0).toString();
                Price = dtm.getValueAt(i, 1).toString();
                Qty = dtm.getValueAt(i, 2).toString();
                Total = dtm.getValueAt(i, 3).toString();

        String sql = "INSERT INTO order_table(Item,Price,Qty,Total)VALUES (?,?,?,?)";
        pst = con.prepareStatement(sql);

        pst.setString(1, Item);
        pst.setString(2, Price);
        pst.setString(3, Qty);
        pst.setString(4, Total);

        pst.execute();
            }
        JOptionPane.showMessageDialog(this, "Order is instered to the Database");
            //Remove all data in Table
                dtm.setRowCount(0);
             }  
            catch (Exception e) {
    }

}
        
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void chkfd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkfd2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkfd2ActionPerformed

    private void chkfd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkfd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkfd1ActionPerformed

    private void chkM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkM1ActionPerformed

    private void chkM3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkM3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkM3ActionPerformed

    private void chkM4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkM4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkM4ActionPerformed

    private void chkM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkM2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkM2ActionPerformed

    private void chkD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkD1ActionPerformed

    private void chkD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkD3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkD3ActionPerformed

    private void chkD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkD4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkD4ActionPerformed

    private void chkD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkD2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkD2ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        //get jtable  modell first
        DefaultTableModel tb1Model = (DefaultTableModel) jTable1.getModel();
        
        //delete row
        if(jTable1.getSelectedRowCount()==1){
            //if single row is selected than delete
            tb1Model.removeRow(jTable1.getSelectedRow());
            
            int sum = 0;
             for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }

        txtbill.setText(Integer.toString(sum));
        }else{
            if(jTable1.getRowCount()==0){
                //if table is empty (no data) than display messege
                JOptionPane.showMessageDialog(this, "Order table is Empty.");
            }else{
                //if table is not empty but row is selected or multiple row is selected
                JOptionPane.showMessageDialog(this, "Please select a Food Item for Remove.");
            }
        }
            
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        LoginGUI guiRegister = new LoginGUI();
            guiRegister.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_btnLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceOrderGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItems;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkD1;
    private javax.swing.JCheckBox chkD2;
    private javax.swing.JCheckBox chkD3;
    private javax.swing.JCheckBox chkD4;
    private javax.swing.JCheckBox chkM1;
    private javax.swing.JCheckBox chkM2;
    private javax.swing.JCheckBox chkM3;
    private javax.swing.JCheckBox chkM4;
    private javax.swing.JCheckBox chkfd1;
    private javax.swing.JCheckBox chkfd2;
    private javax.swing.JCheckBox chkfd3;
    private javax.swing.JCheckBox chkfd4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner spD1;
    private javax.swing.JSpinner spD2;
    private javax.swing.JSpinner spD3;
    private javax.swing.JSpinner spD4;
    private javax.swing.JSpinner spM1;
    private javax.swing.JSpinner spM2;
    private javax.swing.JSpinner spM3;
    private javax.swing.JSpinner spM4;
    private javax.swing.JLabel txtbill;
    private javax.swing.JSpinner txtfd1;
    private javax.swing.JSpinner txtfd2;
    private javax.swing.JSpinner txtfd3;
    private javax.swing.JSpinner txtfd4;
    // End of variables declaration//GEN-END:variables
}
